# Generated by Django 3.1.1 on 2021-02-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=200)),
                ('colourname', models.CharField(max_length=600)),
            ],
        ),
    ]
